### ISSUE TITLE
System env variable

### ISSUE THREAD

**Issue by petrasbut** [ericdallo/spring-s3-properties-loader#9]
I don't think this is working as intended:
```@S3PropertiesLocation(value = "${AWS_S3_LOCATION}", profiles = "developer")```

From the code:
https://github.com/ericdallo/spring-s3-properties-loader/blob/master/src/main/java/com/spring/loader/util/SystemPropertyResolver.java#L48

We can see that the value comes from ```String valueFromEnv = System.getenv(key);``` the env variables.
However, it would be better to fallback into ```System.getProperties```. This way we can pass `-D` params to the JVM.

This is particularly useful with AWS beanstalk with sets env variables as `-D` params on the JVM.

**Comment by ericdallo** [comment]
Thanks for de feedback and idea @petrasbut. Fixed in [version 2.2.3](https://github.com/ericdallo/spring-s3-properties-loader/releases/tag/2.2.3)
